apiVersion: v1
data:
  tempo.yaml: |
    distributor:
        receivers:
            jaeger:
                protocols:
                    grpc:
                        endpoint: 0.0.0.0:14250
            otlp:
                protocols:
                    grpc:
                        endpoint: 0.0.0.0:4317
    http_api_prefix: ""
    memberlist:
        abort_if_cluster_join_fails: false
        bind_addr:
            - '::'
        bind_port: 7946
        join_members:
            - dns+gossip-ring.tracing.svc.cluster.local.:7946
    overrides:
        per_tenant_override_config: /overrides/overrides.yaml
    server:
        grpc_listen_address: ::0
        http_listen_address: ::0
        http_listen_port: 3200
    storage:
        trace:
            azure:
                container_name: tempo
            backend: gcs
            blocklist_poll: "0"
            cache: memcached
            gcs:
                bucket_name: tempo
                chunk_buffer_size: 1.048576e+07
            memcached:
                consistent_hash: true
                host: memcached
                service: memcached-client
                timeout: 200ms
            pool:
                queue_depth: 2000
            s3:
                bucket: tempo
            wal:
                path: /var/tempo/wal
kind: ConfigMap
metadata:
  name: tempo-distributor
  namespace: tracing
