apiVersion: v1
data:
  tempo.yaml: |
    compactor: {}
    distributor: {}
    http_api_prefix: ""
    ingester:
        lifecycler:
            ring:
                replication_factor: 3
    memberlist:
        abort_if_cluster_join_fails: false
        bind_port: 7946
        join_members:
            - gossip-ring.tracing.svc.cluster.local:7946
    overrides:
        per_tenant_override_config: /overrides/overrides.yaml
    search_enabled: false
    server:
        http_listen_port: 3200
    storage:
        trace:
            azure:
                container-name: tempo
            backend: gcs
            blocklist_poll: "0"
            cache: memcached
            gcs:
                bucket_name: tempo
                chunk_buffer_size: 1.048576e+07
            memcached:
                consistent_hash: true
                host: memcached
                service: memcached-client
                timeout: 200ms
            pool:
                queue_depth: 2000
            s3:
                bucket: tempo
            wal:
                path: /var/tempo/wal
kind: ConfigMap
metadata:
  name: tempo-ingester
  namespace: tracing
