apiVersion: v1
data:
  overrides.yaml: |
    overrides: {}
  tempo.yaml: |
    compactor: null
    distributor:
        receivers:
            jaeger:
                protocols:
                    grpc:
                        endpoint: 0.0.0.0:14250
            otlp:
                protocols:
                    grpc:
                        endpoint: 0.0.0.0:55680
    ingester:
        lifecycler:
            ring:
                replication_factor: 3
    memberlist:
        abort_if_cluster_join_fails: false
        bind_port: 7946
        join_members:
          - gossip-ring.tracing.svc.cluster.local:7946
    overrides:
        per_tenant_override_config: /conf/overrides.yaml
    server:
        http_listen_port: 3100
    storage:
        trace:
            backend: gcs
            blocklist_poll: "0"
            cache: memcached
            gcs:
                bucket_name: tempo
                chunk_buffer_size: 1.048576e+07
            memcached:
                consistent_hash: true
                host: memcached
                service: memcached-client
                timeout: 500ms
            pool:
                queue_depth: 2000
            s3:
                bucket: tempo
            wal:
                path: /var/tempo/wal
kind: ConfigMap
metadata:
  name: tempo-distributor
  namespace: tracing
