apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulture
  namespace: tracing
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: vulture
      name: vulture
  template:
    metadata:
      labels:
        app: vulture
        name: vulture
    spec:
      containers:
      - args:
        - -prometheus-listen-address=:8080
        - -tempo-push-url=http://distributor
        - -tempo-query-url=http://query-frontend:3100/tempo
        - -logtostderr=true
        - -tempo-org-id=1
        image: grafana/tempo-vulture:latest
        imagePullPolicy: IfNotPresent
        name: vulture
        ports:
        - containerPort: 8080
          name: prom-metrics
        resources:
          limits:
            cpu: 100m
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 100Mi
