target: all

server:
  http_listen_port: 3200
  log_level: debug

query_frontend:
  search:
    query_backend_after: 1s

distributor:
  receivers:
    jaeger:
      protocols:
        grpc:
    otlp:
      protocols:
        grpc:
    zipkin:
  log_received_spans:
    enabled: true

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  trace_idle_period: 1s
  max_block_bytes: 1
  max_block_duration: 2s
  complete_block_timeout: 1s
  flush_check_period: 3s

storage:
  trace:
    backend: local
    local:
      path: /var/tempo
    pool:
      max_workers: 10
      queue_depth: 100
    block:
      version: vParquet3
    blocklist_poll: 1s
