target: all

server:
  http_listen_port: 3200

query_frontend:
  search:
    query_backend_after: 0 # setting these both to 0 will force all range searches to hit the backend
    query_ingesters_until: 0

distributor:
  receivers:
    jaeger:
      protocols:
        grpc:

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  trace_idle_period: 1s
  max_block_duration: 5s
  complete_block_timeout: 5s
  flush_check_period: 1s

storage:
  trace:
    blocklist_poll: 1s
    backend: azure
    azure:
      container_name: tempo                    # how to store data in azure
      endpoint_suffix: tempo_e2e-azurite:10000
      storage_account_name: "devstoreaccount1"
      storage_account_key: "Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=="
    pool:
      max_workers: 10
      queue_depth: 100