target: all

server:
  http_listen_port: 3200

query_frontend:
  search:
    query_backend_after: 0 # setting these both to 0 will force all range searches to hit the backend
    query_ingesters_until: 0

distributor:
  receivers:
    jaeger:
      protocols:
        grpc:

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  trace_idle_period: 1s
  max_block_duration: 5s
  complete_block_timeout: 5s
  flush_check_period: 1s

storage:
  trace:
    blocklist_poll: 1s
    backend: s3
    s3:
      bucket: tempo
      endpoint: tempo_e2e-minio-9000:9000  # TODO: this is brittle, fix this eventually
      access_key: Cheescake # TODO: use cortex_e2e.MinioAccessKey
      secret_key: supersecret # TODO: use cortex_e2e.MinioSecretKey
      insecure: true
    pool:
      max_workers: 10
      queue_depth: 100