version: "2"
services:

  distributor:
    image: tempo:latest
    command: "-target=distributor -config.file=/etc/tempo.yaml"
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    ports:
      - "14268"  # jaeger ingest
      - "3200"   # tempo
      - "7946"
    depends_on:
      - minio

  ingester-0:
    image: tempo:latest
    command: "-target=ingester -config.file=/etc/tempo.yaml"
    restart: always
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    ports:
      - "14268"  # jaeger ingest
      - "3200"   # tempo
      - "7946"
    depends_on:
      - distributor # inverted relationship here to add delay for minio

  ingester-1:
    image: tempo:latest
    command: "-target=ingester -config.file=/etc/tempo.yaml"
    restart: always
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    ports:
      - "14268"  # jaeger ingest
      - "3200"   # tempo
      - "7946"
    depends_on:
      - distributor # inverted relationship here to add delay for minio

  ingester-2:
    image: tempo:latest
    command: "-target=ingester -config.file=/etc/tempo.yaml"
    restart: always
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    ports:
      - "14268"  # jaeger ingest
      - "3200"   # tempo
      - "7946"
    depends_on:
      - distributor # inverted relationship here to add delay for minio

  minio:
    image: minio/minio:latest
    environment:
      - MINIO_ACCESS_KEY=tempo
      - MINIO_SECRET_KEY=supersecret
    ports:
      - "9000:9000"
    entrypoint:
      - sh
      - -euc
      - mkdir -p /data/tempo && /opt/bin/minio server /data

  synthetic-load-generator:
    image: omnition/synthetic-load-generator:1.0.25
    volumes:
      - ./load-generator.json:/etc/load-generator.json
    environment:
      - TOPOLOGY_FILE=/etc/load-generator.json
      - JAEGER_COLLECTOR_URL=http://distributor:14268
    depends_on:
      - distributor
      - ingester-0
      - ingester-1

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus.yaml
    entrypoint:
      - /bin/prometheus
      - --config.file=/etc/prometheus.yaml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:10.4.19@sha256:a9043254ba16fb10945cc27333963dfd08eccbb43b51f1222d831cc564e3a1f4
    volumes:
      - ./grafana/datasources/:/etc/grafana/provisioning/datasources/
      - ./grafana/dashboards-provisioning/:/etc/grafana/provisioning/dashboards/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8080:8080
    volumes:
    - /var/lib/docker/:/var/lib/docker:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /sys:/sys:ro
