version: "2"
services:

  frigg:
    image: frigg:latest
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - /tmp/tempo:/tmp/tempo
    ports:
      - "14268"      # jaeger
      - "3100:3100"  # frigg

  frigg-query:
    image: frigg-query:latest
    command: ["--grpc-storage-plugin.configuration-file=/etc/tempo-query.yaml"]
    volumes:
      - ./tempo-query.yaml:/etc/tempo-query.yaml
    ports:
      - "16686:16686"  # jaeger-ui

  synthetic-load-generator:
    image: omnition/synthetic-load-generator:1.0.25
    volumes:
      - ./load-generator.json:/etc/load-generator.json
    environment:
      - TOPOLOGY_FILE=/etc/load-generator.json
      - JAEGER_COLLECTOR_URL=http://tempo:14268
    depends_on:
      - frigg

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus.yaml
    entrypoint:
      - /bin/prometheus
      - --config.file=/etc/prometheus.yaml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./datasources:/etc/grafana/provisioning/datasources
      - ./dashboards-provisioning:/etc/grafana/provisioning/dashboards
      - ./dashboards:/var/lib/grafana/dashboards
    #environment:
    #  - GF_AUTH_ANONYMOUS_ENABLED=true
    ports:
      - "3000:3000"