version: "2"
services:

  tempo:
    image: grafana/tempo:latest
    entrypoint:
      - sh
      - -euc
      - sleep 5 && /tempo -config.file=/etc/tempo.yaml
    volumes:
      - ./etc/tempo-s3-minio.yaml:/etc/tempo.yaml
      - ./example-data/tempo:/tmp/tempo
    ports:
      - "14268"      # jaeger
      - "3100:3100"  # tempo
    depends_on: 
      - minio

  minio:
    image: minio/minio:RELEASE.2021-05-26T00-22-46Z
    environment:
      - MINIO_ACCESS_KEY=tempo
      - MINIO_SECRET_KEY=supersecret
    ports:
      - "9000:9000"
    entrypoint:
      - sh
      - -euc
      - mkdir -p /data/tempo && /usr/bin/minio server /data

  synthetic-load-generator:
    image: omnition/synthetic-load-generator:1.0.25
    volumes:
      - ./etc/load-generator.json:/etc/load-generator.json
    environment:
      - TOPOLOGY_FILE=/etc/load-generator.json
      - JAEGER_COLLECTOR_URL=http://tempo:14268
    depends_on:
      - tempo

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./etc/prometheus.yaml:/etc/prometheus.yaml
    entrypoint:
      - /bin/prometheus
      - --config.file=/etc/prometheus.yaml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:7.5.1
    volumes:
      - ./example-data/datasources:/etc/grafana/provisioning/datasources
      - ./example-data/dashboards-provisioning:/etc/grafana/provisioning/dashboards
      - ../../operations/tempo-mixin/out:/var/lib/grafana/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"