services:

  tempo1:
    image: grafana/tempo:latest
    command: "-target=scalable-single-binary -config.file=/etc/tempo.yaml"
    volumes:
      - ./tempo-scalable-single-binary.yaml:/etc/tempo.yaml
    restart: always
    networks:
      default:
        aliases:
          - tempo
    depends_on:
      - minio
    ports:
      - 3200:3200

  tempo2:
    image: grafana/tempo:latest
    command: "-target=scalable-single-binary -config.file=/etc/tempo.yaml"
    volumes:
      - ./tempo-scalable-single-binary.yaml:/etc/tempo.yaml
    restart: always
    networks:
      default:
        aliases:
          - tempo
    depends_on:
      - minio

  tempo3:
    image: grafana/tempo:latest
    command: "-target=scalable-single-binary -config.file=/etc/tempo.yaml"
    volumes:
      - ./tempo-scalable-single-binary.yaml:/etc/tempo.yaml
    restart: always
    networks:
      default:
        aliases:
          - tempo
    depends_on:
      - minio

  vulture:
    image: grafana/tempo-vulture:latest
    command:
      - "-prometheus-listen-address=:3201"
      - "-tempo-push-url=http://tempo1"
      - "-tempo-query-url=http://tempo1:3200"
      - "-tempo-retention-duration=1h"

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
    volumes:
      - ./prometheus.yaml:/etc/prometheus.yaml

  grafana:
    image: grafana/grafana:12.3.0@sha256:70d9599b186ce287be0d2c5ba9a78acb2e86c1a68c9c41449454d0fc3eeb84e8
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    ports:
      - 3000:3000

  seaweedfs:
    image: chrislusf/seaweedfs:latest
    command: 'server -s3 -s3.port=9000 -s3.config=/etc/seaweedfs/s3.json -dir=/data'
    volumes:
      - ../shared/seaweedfs-s3.json:/etc/seaweedfs/s3.json:ro
    ports:
      - "9000:9000"

  k6-tracing:
    image: ghcr.io/grafana/xk6-client-tracing:v0.0.9
    environment:
      - ENDPOINT=tempo1:4317
    restart: always
    depends_on:
      - tempo1
