retention: 48h
storage:
  capacity: 30G
  storageClassName: local-path
backend:
  backend: s3
  s3:
    access_key: tempo
    bucket: tempo
    endpoint: minio:9000
    insecure: true
    secret_key: supersecret
distributor:
  replicas: 2
  image: grafana/tempo:latest
  resources:
    requests:
      cpu:      1
      memory:   500Mi
  receivers:
    jaeger:
      protocols:
        thrift_http: null
compactor:
  replicas: 1
  image: grafana/tempo:latest
  resources:
    requests:
      cpu:      250m
      memory:   1Gi
ingester:
  replicas: 3
  image: grafana/tempo:latest
  resources:
    requests:
      cpu:      1
      memory:   1.5Gi
resources:
  image: grafana/tempo:latest
  resources:
    requests:
      cpu:      500m
      memory:   2Gi
querier:
  replicas: 1
  image: grafana/tempo:latest
  resources:
    requests:
      cpu:      250m
      memory:   500Mi
tempoQuery:
  image: grafana/tempo-query:latest
  resources:
    requests:
      cpu:      50m
      memory:   100Mi
memcached:
  image: memcached:1.5.17-alpine
  replicas: 0