[package]
name = "traceql"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
datafusion = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
test_each_file = "0.3"
