services:

  # tempo - a
  distributor-a:
    image: &tempoImage grafana/tempo:latest
    command: "-target=distributor -config.file=/etc/tempo.yaml"
    restart: always
    volumes:
      - ./tempo-distributed-a.yaml:/etc/tempo.yaml
    ports:
      - "3200"   # tempo

  ingester-0-a:
    image: *tempoImage
    command: "-target=ingester -config.file=/etc/tempo.yaml"
    restart: always
    volumes:
      - ./tempo-distributed-a.yaml:/etc/tempo.yaml
    ports:
      - "3200"   # tempo

  ingester-1-a:
    image: *tempoImage
    command: "-target=ingester -config.file=/etc/tempo.yaml"
    restart: always
    volumes:
      - ./tempo-distributed-a.yaml:/etc/tempo.yaml
    ports:
      - "3200"   # tempo

  ingester-2-a:
    image: *tempoImage
    command: "-target=ingester -config.file=/etc/tempo.yaml"
    restart: always
    volumes:
      - ./tempo-distributed-a.yaml:/etc/tempo.yaml
    ports:
      - "3200"   # tempo

  query-frontend-a:
    image: *tempoImage
    command: "-target=query-frontend -config.file=/etc/tempo.yaml"
    restart: always
    volumes:
      - ./tempo-distributed-a.yaml:/etc/tempo.yaml
    ports:
      - "3200"   # tempo

  querier-a:
    image: *tempoImage
    command: "-target=querier -config.file=/etc/tempo.yaml"
    restart: always
    volumes:
      - ./tempo-distributed-a.yaml:/etc/tempo.yaml
    ports:
      - "3200"   # tempo

  compactor-a:
    image: *tempoImage
    command: "-target=compactor -config.file=/etc/tempo.yaml"
    restart: always
    volumes:
      - ./tempo-distributed-a.yaml:/etc/tempo.yaml
    ports:
      - "3200"   # tempo

  metrics-generator-a:
    image: *tempoImage
    command: "-target=metrics-generator -config.file=/etc/tempo.yaml"
    restart: always
    volumes:
      - ./tempo-distributed-a.yaml:/etc/tempo.yaml
    ports:
      - "3200"   # tempo

  # tempo - b
  #  there is purposefully no compactor-b. only one cell can compactor or there will be job collisions
  distributor-b:
    image: *tempoImage
    command: "-target=distributor -config.file=/etc/tempo.yaml"
    restart: always
    volumes:
      - ./tempo-distributed-b.yaml:/etc/tempo.yaml
    ports:
      - "3200"   # tempo

  ingester-0-b:
    image: *tempoImage
    command: "-target=ingester -config.file=/etc/tempo.yaml"
    restart: always
    volumes:
      - ./tempo-distributed-b.yaml:/etc/tempo.yaml
    ports:
      - "3200"   # tempo

  ingester-1-b:
    image: *tempoImage
    command: "-target=ingester -config.file=/etc/tempo.yaml"
    restart: always
    volumes:
      - ./tempo-distributed-b.yaml:/etc/tempo.yaml
    ports:
      - "3200"   # tempo

  ingester-2-b:
    image: *tempoImage
    command: "-target=ingester -config.file=/etc/tempo.yaml"
    restart: always
    volumes:
      - ./tempo-distributed-b.yaml:/etc/tempo.yaml
    ports:
      - "3200"   # tempo

  query-frontend-b:
    image: *tempoImage
    command: "-target=query-frontend -config.file=/etc/tempo.yaml"
    restart: always
    volumes:
      - ./tempo-distributed-b.yaml:/etc/tempo.yaml
    ports:
      - "3200"   # tempo

  querier-b:
    image: *tempoImage
    command: "-target=querier -config.file=/etc/tempo.yaml"
    restart: always
    volumes:
      - ./tempo-distributed-b.yaml:/etc/tempo.yaml
    ports:
      - "3200"   # tempo

  metrics-generator-b:
    image: *tempoImage
    command: "-target=metrics-generator -config.file=/etc/tempo.yaml"
    restart: always
    volumes:
      - ./tempo-distributed-b.yaml:/etc/tempo.yaml
    ports:
      - "3200"   # tempo

  seaweedfs:
    image: chrislusf/seaweedfs:latest
    command: 'server -s3 -s3.port=9000 -s3.config=/etc/seaweedfs/s3.json -dir=/data'
    volumes:
      - ../shared/seaweedfs-s3.json:/etc/seaweedfs/s3.json:ro
    ports:
      - "9000:9000"

  k6-tracing:
    image: ghcr.io/grafana/xk6-client-tracing:v0.0.9
    environment:
      - ENDPOINT=distributor-a:4317
    restart: always
    depends_on:
      - distributor-a

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
    volumes:
      - ./prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:12.3.0@sha256:70d9599b186ce287be0d2c5ba9a78acb2e86c1a68c9c41449454d0fc3eeb84e8
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    ports:
      - "3000:3000"
