target: all
stream_over_http_enabled: true

server:
  http_listen_port: 3200
  log_level: info

query_frontend:
  rf1_after: "2025-01-01T00:00:00Z"
  query_end_cutoff: 0 # Include all recent data
  search:
    query_backend_after: 30s
    query_ingesters_until: 30s

distributor:
  receivers:
    jaeger:
      protocols:
        grpc:
          endpoint: "tempo:14250"
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
  log_received_spans:
    enabled: true
  log_discarded_spans:
    enabled: true

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
    min_ready_duration: 1s
  trace_idle_period: 1s
  max_block_bytes: 1
  max_block_duration: 2s
  complete_block_timeout: 20s
  flush_check_period: 1s
  partition_ring:
    kvstore:
      store: inmemory
  flush_object_storage: false

storage:
  trace:
    backend: local
    local:
      path: /var/tempo
    pool:
      max_workers: 10
      queue_depth: 100
    block:
      version: vParquet3
    blocklist_poll: 1s

overrides:
  user_configurable_overrides:
    enabled: true
    poll_interval: 10s
    client:
      backend: local
      local:
        path: /var/tempo/overrides

block_builder:
  consume_cycle_duration: 1m

ingest:
  enabled: true
  kafka:
    address: kafka:9092
    topic: tempo-ingest
