apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    grafana.com/inject-rollout-operator-ca: "true"
    grafana.com/namespace: tracing
  name: pod-eviction-tracing
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: rollout-operator
      namespace: tracing
      path: /admission/pod-eviction
      port: 443
  failurePolicy: Fail
  name: pod-eviction-tracing.grafana.com
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: tracing
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods/eviction
    scope: Namespaced
  sideEffects: None
