metrics_generator:
  processor:
    service_graphs:
      histogram_buckets: [1, 2]  # seconds
    span_metrics:
      histogram_buckets: [1, 2]
  registry:
    collection_interval: 1s
  storage:
    path: /var/tempo
    remote_write:
      - url: http://tempo_e2e-prometheus:9090/api/v1/write
        send_exemplars: true

overrides:
  defaults:
    metrics_generator:
      max_active_series: 1000
      processor:
        span_metrics:
          enable_target_info: true
