version: "3"
services:

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo-gcs.yaml:/etc/tempo.yaml
      - ./tempo-data:/tmp/tempo
    ports:
      - "14268"      # jaeger
      - "3200:3200"  # tempo
    depends_on:
      - gcs

  gcs:
    image: fsouza/fake-gcs-server
    command: [ "-public-host=gcs -port=4443"]
    ports:
      - "4443:4443"
    volumes:
      # This creates an empty tempo bucket
      - ./gcs-data/:/data/tempo/

  synthetic-load-generator:
    image: omnition/synthetic-load-generator:1.0.25
    volumes:
      - ../shared/load-generator.json:/etc/load-generator.json
    environment:
      - TOPOLOGY_FILE=/etc/load-generator.json
      - JAEGER_COLLECTOR_URL=http://tempo:14268
    depends_on:
      - tempo

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ../shared/prometheus.yaml:/etc/prometheus.yaml
    command: --config.file=/etc/prometheus.yaml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:7.5.7
    volumes:
      - ../shared/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
