apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  uid: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus:9090
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
  jsonData:
    httpMethod: GET
- name: Tempo (both tenants)
  type: tempo
  access: proxy
  orgId: 1
  url: http://tempo:3200
  basicAuth: false
  isDefault: true
  version: 1
  editable: false
  apiVersion: 1
  uid: tempo-both
  jsonData:
    httpMethod: GET
    httpHeaderName1: 'X-Scope-Orgid'
  secureJsonData:
    httpHeaderValue1: 'tenant-1|tenant-2'
- name: Tempo (tenant-1)
  type: tempo
  access: proxy
  orgId: 1
  url: http://tempo:3200
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
  apiVersion: 1
  uid: tempo-tenant-1
  jsonData:
    httpMethod: GET
    httpHeaderName1: 'X-Scope-Orgid'
  secureJsonData:
    httpHeaderValue1: 'tenant-1'
- name: Tempo (tenant-2)
  type: tempo
  access: proxy
  orgId: 1
  url: http://tempo:3200
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
  apiVersion: 1
  uid: tempo-tenant-2
  jsonData:
    httpMethod: GET
    httpHeaderName1: 'X-Scope-Orgid'
  secureJsonData:
    httpHeaderValue1: 'tenant-2'
- name: Tempo (vulture)
  type: tempo
  access: proxy
  orgId: 1
  url: http://tempo:3200
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
  apiVersion: 1
  uid: tempo-vulture
  jsonData:
    httpMethod: GET
    httpHeaderName1: 'X-Scope-Orgid'
  secureJsonData:
    httpHeaderValue1: 'vulture-tenant'