apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-querier
  namespace: default
data:
  tempo.yaml: |
    auth_enabled: false
    memberlist:
        abort_if_cluster_join_fails: false
        bind_port: 7946
        join_members:
          - gossip-ring.default.svc.cluster.local:7946
    overrides:
        per_tenant_override_config: /conf/overrides.yaml
    server:
        http_listen_port: 3100
        log_level: debug
    storage:
        trace:
            {{- toYaml .Values.backend | nindent 12 }}
            maintenance_cycle: 5m
            memcached:
                consistent_hash: true
                host: memcached
                service: memcached-client
                timeout: 1s
            pool:
                max_workers: 200
                queue_depth: 2000
            wal:
                path: /var/tempo/wal