apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo
data:
  overrides.yaml: |
    overrides: {}
  tempo.yaml: |
    auth_enabled: false
    compactor: null
    distributor:
        receivers:
            jaeger:
                protocols:
                    thrift_http: null
            opencensus: null
    ingester:
        lifecycler:
            ring:
                replication_factor: 2
    memberlist:
        abort_if_cluster_join_fails: false
        bind_port: 7946
        join_members:
          - gossip-ring.default.svc.cluster.local:7946
    overrides:
        per_tenant_override_config: /conf/overrides.yaml
    server:
        http_listen_port: 3100
    storage:
        trace:
            {{- toYaml .Values.backend | nindent 12 }}
            blocklist_poll: '0'
            cache: memcached
            memcached:
                consistent_hash: true
                host: memcached
                service: memcached-client
                timeout: 500ms
            pool:
                queue_depth: 2000
            wal:
                path: /var/tempo/wal