name: Github repo and issue stats collection
on:
  schedule:
    - cron: "*/30 * * * *"

permissions: {}

jobs:
  main:
    # this action keeps failing in all forks, only run in grafana/tempo.
    # stats collection action is only useful in main repo.
    if: github.repository == 'grafana/tempo'
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Get Github App secrets from vault
        id: get-secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@d8a9c5f93da5baf14c1669f30cb4366f87804640 #get-vault-secrets 1.2.0
        with:
          export_env: false
          repo_secrets: |
            APP_ID=tempo-ci-app:app-id
            PRIVATE_KEY=tempo-ci-app:private-key
      - name: Get app token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: get-github-app-token
        with:
          app-id: ${{ fromJSON(steps.get-secrets.outputs.secrets).APP_ID }}
          private-key: ${{ fromJSON(steps.get-secrets.outputs.secrets).PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: tempo
      - name: Checkout Actions
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          repository: "grafana/grafana-github-actions"
          path: ./actions
          ref: main
          persist-credentials: false
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Run metrics collector
        uses: ./actions/metrics-collector
        with:
          metricsWriteAPIKey: ${{secrets.GRAFANA_MISC_STATS_API_KEY}}
          token: ${{ steps.get-github-app-token.outputs.token }}
