name: Github repo and issue stats collection
on:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  main:
    # this action keeps failing in all forks, only run in grafana/tempo.
    # stats collection action is only useful in main repo.
    if: github.repository == 'grafana/tempo'
    runs-on: ubuntu-24.04
    steps:
      - name: Get app token
        uses: actions/create-github-app-token@v2
        id: get-github-app-token
        with:
          app-id: ${{secrets.APP_ID}}
          private-key: ${{secrets.APP_PRIVATE_KEY}}
          owner: ${{ github.repository_owner }}
      - name: Checkout Actions
        uses: actions/checkout@v4
        with:
          repository: "grafana/grafana-github-actions"
          path: ./actions
          ref: main
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Run metrics collector
        uses: ./actions/metrics-collector
        with:
          metricsWriteAPIKey: ${{secrets.GRAFANA_MISC_STATS_API_KEY}}
          token: ${{ steps.get-github-app-token.outputs.token }}
