name: Milestoned issue to Tempo Squad Project.

on:
  # Triggers the workflow on when an issue is milestoned.
  issues:
    types: [milestoned]
    
jobs:
  build:
    # only run in grafana/tempo.
    if: github.repository == 'grafana/tempo'
    runs-on: ubuntu-24.04

    steps:
      - name: Get app token
        uses: actions/create-github-app-token@v2
        id: get-github-app-token
        with:
          app-id: ${{secrets.APP_ID}}
          private-key: ${{secrets.APP_PRIVATE_KEY}}
          owner: ${{ github.repository_owner }}
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/grafana/projects/135
          github-token: ${{ steps.get-github-app-token.outputs.token }}
