name: Milestoned issue to Tempo Squad Project.

on:
  # Triggers the workflow on when an issue is milestoned.
  issues:
    types: [milestoned]

permissions: {}

jobs:
  build:
    # only run in grafana/tempo.
    if: github.repository == 'grafana/tempo'
    runs-on: ubuntu-24.04

    steps:
      - name: Get Github App secrets from vault
        id: get-secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@5d7e361bc7e0a183cde8afe9899fb7b596d2659b #get-vault-secrets 1.2.0
        with:
          repo_secrets: |
            APP_ID=tempo-ci-app:app-id
            PRIVATE_KEY=tempo-ci-app:private-key
      - name: Get app token
        uses: actions/create-github-app-token@3ff1caaa28b64c9cc276ce0a02e2ff584f3900c5 # v2.0.2
        id: get-github-app-token
        with:
          app-id: ${{ fromJSON(steps.get-secrets.outputs.secrets).APP_ID }}
          private-key: ${{ fromJSON(steps.get-secrets.outputs.secrets).PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/grafana/projects/135
          github-token: ${{ steps.get-github-app-token.outputs.token }}
