name: Stale check
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * *'
permissions:
  issues: write
  pull-requests: write
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v7.0.0
        with:
          close-issue-reason: not_planned
          operations-per-run: 100
          days-before-stale: 60
          days-before-close: 15
          stale-issue-message: >
            This issue has been automatically marked as stale because it has
            not had any activity in the past 60 days.

            The next time this stale check runs, the stale label will be
            removed if there is new activity. The issue will be closed after 15
            days if there is no new activity.

            Please apply keepalive label to exempt this Issue.
          stale-pr-message: >
            This PR has been automatically marked as stale because it has not
            had any activity in the past 60 days.

            The next time this stale check runs, the stale label will be
            removed if there is new activity. This pull request will be closed in 15
            days if there is no new activity.

            Please apply keepalive label to exempt this Pull Request.
          stale-issue-label: stale
          stale-pr-label: stale
          exempt-issue-labels: keepalive,dependencies,bug
          exempt-pr-labels: keepalive,dependencies,bug
